Implementing autoscroll feature
Sangwan5688/BlackHole pull request #275
Opened 2022-03-30 16:15 UTC by BrightDV

Hello!

I have finally managed to implement the autoscroll feature in the `SlidingUpPanel`. I used a `ValueListenableBuilder` and utilized the gradientColor as the `valueListenable`.

Now:

*   When the user plays a new song, it autoscrolls if the player is open or closed, but only once.
*   When the song played is one of the 3 last, it doesn't autoscroll because otherwise it was buggy and scrolled under the \`List\`…
*   One thing is when the song played isn't the first one and coming from another screen, the `SlidingUpPanel` autoscrolls after the user moves the List

Also, there was a problem with the height of the `Text` but I have added 12dp plus the index \* height of a ListTile (72dp) so now this is fixed!

2022-04-14 18:56 UTC, Sangwan5688 reviewed
Ok, so i checked the code. Everything looks fine in the code. But when I tried running the app, it doesn't autoscroll until unless I scroll it atleast once. It autoscrolls only after I scroll it once, otherwise not

2022-04-15 17:55 UTC, BrightDV commented
> But when I tried running the app, it doesn't autoscroll until unless I scroll it atleast once. It autoscrolls only after I scroll it once, otherwise not

It is what I meant in

> *   One thing is when the song played isn't the first one and coming from another screen, the `SlidingUpPanel` autoscrolls after the user moves the List

I have tried many ways, but it never autoscrolls by itself, I don't know if you have an idea?

2022-04-16 04:27 UTC, Sangwan5688 commented
I see. Umm, one thing you can do is to move that autoscroll function to audioplayer screen instead of keeping it inside upnext menu. I think the controller is being provided by audioplayer screen so you will be able to scroll it from there. Then you can just check the initial position from there and try it. Most probably it should work.

2022-04-16 12:49 UTC, BrightDV commented
So I have tried to wrap the `ClipRRect` inside a `StreamBuilder`, in order to access the `audioHandler.queueState` data.
However, the problem is still here, it doesn't autoscroll the first time…
I will push the commit that I made, but they don't fix the problem.

2022-04-20 07:51 UTC, Sangwan5688 commented
Ok, I will have to check it then.

2022-11-03 11:43 UTC, BrightDV commented
I will try to reimplement it from scratch in the next days, so I have reverted my past commits.

2022-11-05 05:51 UTC, Sangwan5688 commented
That much is fine ig. You can look for the fix later on in another PR

2022-11-05 05:56 UTC, Sangwan5688 requested changes
There's probably some formatting issue too which is causing the build check to fail, fix that too

2022-11-05 05:56 UTC, Sangwan5688 commented on lib/Screens/Player/audioplayer.dart
> +    int? itemIndex,
why `int?`? make it `int` you can use itemIndex ?? 0 while calling this function

2022-11-05 05:56 UTC, Sangwan5688 commented on lib/Screens/Player/audioplayer.dart
> +    queue,
give a type to `queue` otherwise `queue.length` will have issue. And I don't think there's a need for queue at all, just pass it as `int queueLength`

2022-11-05 05:56 UTC, Sangwan5688 commented on lib/Screens/Player/audioplayer.dart
> +    } else if (queue.length - queuePosition < 5) {
`queue.length` will change to `queueLength`

2022-11-05 05:56 UTC, Sangwan5688 commented on lib/Screens/Player/audioplayer.dart
> +          queue,
`queueState.queueIndex` to `queueState.queueIndex ?? 0`
`queue` to `queue.length`

2022-11-05 05:56 UTC, Sangwan5688 commented on lib/Screens/Player/audioplayer.dart
> +                    );
same as described above

2022-11-06 03:55 UTC, Sangwan5688 commented
LGTM

2022-11-06 03:55 UTC, merged