Fixed the system navbar behaviour on theme change
Sangwan5688/BlackHole pull request #590
Opened 2023-05-26 20:04 UTC by k12onoss

I made the system navigation bar (and status bar) transparent and set the SystemUiMode property to edgeToEdge so as to keep up with the latest android designing guidelines. It also fixes the problem of the status bar elements being hidden in some cases.

2023-05-27 08:02 UTC, Sangwan5688 commented
When you learnt flutter? Anyways, some screens aren't inside safe area, coz of which navigation bar will show over the app UI. Can you please fix those, also please dart format the files too. Some aren't formatted, which is breaking the build.

2023-05-27 08:36 UTC, k12onoss commented
Learnt it over the last year :).

> navigation bar will show over the app UI

Yes, that is the intended outcome. Most system apps in Android (and all apps on iOS) have the navigation bar floating over the app UI. I think it looks much better in comparison.

Anyways, I have reformatted the code, so it shouldn't fail now.

2023-05-27 09:15 UTC, Sangwan5688 commented
I get that, but some parts of the app will be inaccessible on some screens. Let's take miniplayer for example. The screens which are inside safearea, those will work just fine, but for screens which aren't inside safe area the miniplayer will show below the navigation bar. It's not an issue with the gesture navigation bar, but with 3 buttons, miniplayer won't be accessible at all.

2023-05-27 15:37 UTC, k12onoss commented
Ahh, okay. Wrapped the miniplayer and madeBy text within the SafeArea widget. Let me know if there are any other components that should be wrapped.

2023-05-28 05:47 UTC, Sangwan5688 requested changes

2023-05-28 05:47 UTC, Sangwan5688 commented on lib/main.dart
> +        : AuthScreen();g
umm?

2023-05-28 05:58 UTC, Sangwan5688 commented on lib/main.dart
> +        : AuthScreen();g
```suggestion
        : AuthScreen();
```

2023-05-28 05:59 UTC, merged